import {
  FiLayers,
  FiServer,
  FiCpu,
  FiShoppingCart,
  FiMessageSquare,
  FiMessageCircle,
  FiMapPin,
  FiShare2,
  FiRadio,
  FiGlobe,
  FiLinkedin,
  FiGithub,
  FiInstagram,
  FiFacebook,
  FiMail,
  FiPhone,
  FiArrowRight,
  FiArrowUpRight,
  FiCheckCircle,
  FiCheck,
  FiMenu,
  FiX,
  FiMoon,
  FiSun,
  FiZap,
  FiStar,
  FiEye,
  FiExternalLink,
} from 'react-icons/fi';
import {
  FaBasketballBall,
  FaFutbol,
  FaBrain,
  FaGhost,
  FaFlask,
  FaRocket,
  FaSatelliteDish,
  FaTerminal,
} from 'react-icons/fa';
import { GiMagicGate, GiSatelliteCommunication } from 'react-icons/gi';
import { LuRadar, LuSparkles } from 'react-icons/lu';

const map = {
  layers: FiLayers,
  server: FiServer,
  chip: FiCpu,
  cart: FiShoppingCart,
  chat: FiMessageSquare,
  'chat-bubble': FiMessageCircle,
  map: FiMapPin,
  share: FiShare2,
  antenna: FiRadio,
  network: LuRadar,
  sparkles: LuSparkles,
  rocket: FaRocket,
  brain: FaBrain,
  ghost: FaGhost,
  flask: FaFlask,
  basketball: FaBasketballBall,
  football: FaFutbol,
  zap: FiZap,
  globe: FiGlobe,
  satellite: FaSatelliteDish,
  terminal: FaTerminal,
  portal: GiMagicGate,
  comm: GiSatelliteCommunication,
  linkedin: FiLinkedin,
  github: FiGithub,
  instagram: FiInstagram,
  facebook: FiFacebook,
  mail: FiMail,
  phone: FiPhone,
  arrowRight: FiArrowRight,
  arrowUpRight: FiArrowUpRight,
  checkCircle: FiCheckCircle,
  check: FiCheck,
  menu: FiMenu,
  close: FiX,
  moon: FiMoon,
  sun: FiSun,
  bolt: FiZap,
  star: FiStar,
  eye: FiEye,
  external: FiExternalLink,
};

// Renders a consistent-stroke icon by name. Decor is a convenience that lets
// parent components size it, since react-icons size is controlled inline.
export default function Icon({ name, className = '', size = '1em' }) {
  const Cmp = map[name] || FiGlobe;
  return <Cmp className={className} size={size} aria-hidden="true" focusable="false" />;
}
